#raise Exception("Meaningful message indicating the source of the error")

def hello():
    return "Hello, World!"
    pass
